(defparameter *candidate-run-main* nil)
(load (merge-pathnames "../specialty-specific/train-candidate-map.lisp" (make-pathname :name nil :type nil :defaults *load-truename*)))
(test-cases:deftest awrs-fold-isolation-and-counts
 (let* ((a (read-form-file (candidate-path "smc-trainer/candidate-awrs-deployed.sexp")))
        (report (read-form-file (candidate-path "output/candidate-awrs-validation.sexp")))
        (rows (getf a :observations)) (ids nil) (correct 0))
  (dolist (fold (getf report :folds))
   (let ((train (getf fold :training-ids)) (test (getf fold :validation-ids)))
    (test-cases:check (null (intersection train test :test #'equal)))
    (setf ids (append test ids))
    (dolist (id test)
     (let ((r (find id rows :test #'equal :key (lambda (r) (getf r :id)))))
      (dolist (s rows)
       (when (or (= (getf r :group) (getf s :group)) (equal (getf r :input) (getf s :input)))
        (test-cases:check (not (member (getf s :id) train :test #'equal)))))))
    (incf correct (count-if (lambda (p) (equal (getf p :actual) (getf p :predicted))) (getf (getf fold :metrics) :predictions)))))
  (test-cases:check-equal 117 (length (remove-duplicates ids :test #'equal)))
  (test-cases:check-equal 117 (length ids))
  (test-cases:check-equal (getf report :correct) correct)
  (dolist (r rows) (test-cases:check-equal 9 (length (getf r :question-values))))))
