(defparameter *nine-validation-main* nil)
(load (merge-pathnames "../specialty-specific/validate-nine-model.lisp" (make-pathname :name nil :type nil :defaults *load-truename*)))
(test-cases:deftest rbf-solver-independent-oracle
 (let* ((a (make-array '(2 2) :element-type 'double-float :initial-contents '((0d0 2d0) (3d0 1d0))))
        (b (make-array '(2 1) :element-type 'double-float :initial-contents '((4d0) (5d0))))
        (x (rbf-solve a b)))
  (test-cases:check (< (abs (- (aref x 0 0) 1d0)) 1d-12))
  (test-cases:check (< (abs (- (aref x 1 0) 2d0)) 1d-12))
  (test-cases:check (= (aref a 0 0) 0d0))))
(test-cases:deftest rbf-fits-known-smooth-values
 (let ((model (rbf-fit '((0d0) (1d0) (2d0)) '((0d0) (1d0) (4d0)) 1d0 1d-8)))
  (loop for x in '(0d0 1d0 2d0) do (test-cases:check (< (abs (- (first (rbf-predict model (list x))) (* x x))) 1d-6)))
  (test-cases:check-signals error (rbf-fit '((0d0)) '((1d0)) 0d0 .1d0))))
(test-cases:deftest grouped-cross-validation-isolation
 (let* ((report (read-form-file (candidate-path "output/candidate-nine-cross-validation.sexp")))
        (rows (nine-observations)) (seen nil))
  (dolist (fold (getf report :folds))
   (let ((train (getf fold :training-ids)) (test (getf fold :validation-ids)))
    (test-cases:check (null (intersection train test :test #'equal)))
    (setf seen (append test seen))
    (dolist (id test)
     (let ((r (find id rows :key (lambda (r) (getf r :id)) :test #'equal)))
      (dolist (other rows)
       (when (or (= (getf r :group) (getf other :group)) (equal (getf r :input) (getf other :input)))
        (test-cases:check (not (member (getf other :id) train :test #'equal)))))))))
  (test-cases:check (= 143 (length seen) (length (remove-duplicates seen :test #'equal))))))
(test-cases:deftest validation-counts-match-predictions
 (let* ((r (read-form-file (candidate-path "output/candidate-nine-cross-validation.sexp")))
        (predictions (loop for f in (getf r :folds) append (getf (getf f :metrics) :predictions))))
  (test-cases:check-equal (getf r :correct) (count-if (lambda (p) (equal (getf p :actual) (getf p :predicted))) predictions))
  (test-cases:check (> (/ (getf r :correct) (getf r :total)) .8d0))))
(test-cases:deftest nine-features-and-source-integrity
 (let ((rows (nine-observations)) (a (read-form-file (candidate-path "smc-trainer/candidate-nine-deployed.sexp"))))
  (test-cases:check-equal 9 (length (getf a :feature-schema)))
  (loop for r in rows for saved in (getf a :observations) do
   (test-cases:check-equal (getf r :input) (getf saved :input))
   (test-cases:check-equal (getf r :target) (getf saved :target))
   (test-cases:check-equal (getf r :cluster) (getf saved :cluster))
   (test-cases:check (every (lambda (v) (and (= v v) (< (abs v) 1d6))) (getf (nine-predict a (getf r :input)) :point))))))
(test-cases:deftest awrs-search-excludes-holdout
 (let* ((report (read-form-file (candidate-path "output/candidate-nine-awrs.sexp")))
        (held (remove :train (nine-observations) :key (lambda (r) (getf r :split)))))
  (test-cases:check-equal 25 (length (getf report :evaluations)))
  (dolist (r held) (test-cases:check (not (member (getf r :id) (getf report :fit-ids) :test #'equal))))))
