;;;; Prepare three self-contained root HTML files for GitHub Pages.
(load (merge-pathnames "build-awrs-html.lisp" (make-pathname :name nil :type nil :defaults *load-truename*)))
(defun publication-fragment (text start-marker end-marker &optional (offset 0))
 (let* ((start (or (search start-marker text :start2 offset) (error "Missing ~A" start-marker)))
        (end (or (search end-marker text :start2 (+ start (length start-marker))) (error "Missing ~A" end-marker))))
  (subseq text start (+ end (length end-marker)))))
(defun publication-write (name text)
 (with-open-file (s (candidate-path name) :direction :output :if-exists :supersede)
  (write-string text s)))
(defparameter *publication-nav*
 "<nav aria-label='Pages'><a href='index.html'>Reference</a> · <a href='awrs-smc.html'>Best AWRS-SMC sample</a> · <a href='ref-awrs-smc-compar.html'>Comparison</a> · <a href='https://github.com/FemtoEmacs/specialty-umap'>GitHub repository</a></nav>")
(let* ((page (file-text (candidate-path "output/specialty-awrs-result.html")))
       (style (publication-fragment page "<style>" "</style>"))
       (result (read-form-file (candidate-path "output/candidate-nine-awrs.sexp")))
       (reference (getf result :best-recipe))
       (ranked (sort (copy-list (getf result :evaluations)) #'> :key (lambda (e) (getf (getf e :metrics) :quality))))
       (alternative (find-if (lambda (e) (not (equal reference (getf e :recipe)))) ranked))
       (panels nil) (offset 0))
 (dotimes (i 4)
  (let ((panel (publication-fragment page "<section>" "</section>" offset)))
   (push panel panels)
   (setf offset (+ (search panel page :start2 offset) (length panel)))))
 (setf panels (nreverse panels))
 ;; Preserve the existing landing page once; later rebuilds do not overwrite the backup.
 (when (and (probe-file (candidate-path "index.html"))
            (not (probe-file (candidate-path "output/index-before-awrs-publication.html"))))
  (publication-write "output/index-before-awrs-publication.html" (file-text (candidate-path "index.html"))))
 (loop for name in '("index.html" "awrs-smc.html")
       for title in '("Reference UMAP" "AWRS-SMC — best sampled alternative")
       for entry in (list (list :recipe reference :metrics (getf result :best)) alternative)
       for selected-panels in (list (subseq panels 0 2) (subseq panels 2 4))
       for is-reference = t then nil do
  (publication-write name
   (with-output-to-string (out)
    (format out "<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>~A — Specialty UMAP</title>~A</head><body>~A<h1>~A</h1>" title style *publication-nav* title)
    (format out "<p>~A</p>" (if is-reference "The reference recipe had the highest quality score among the reference and 24 sampled alternatives." "This is the highest-scoring sampled alternative, excluding the reference. Its score was slightly lower than the reference; it was not selected to replace the deployed map."))
    (format out "<p>117 training specialties · all nine features · 250 UMAP epochs per seed. These are the search-sample maps, not the deployed 143-specialty atlas. Unclustered points are marked <strong>+</strong>. Hover over points for their specialty names.</p>")
    (let ((m (getf entry :metrics)))
     (format out "<table><tr><th>Combined quality</th><th>Neighbor recall</th><th>Two-seed stability</th><th>Coverage</th></tr><tr><td>~,4F</td><td>~,1F%</td><td>~,4F</td><td>~,1F%</td></tr></table>" (getf m :quality) (* 100 (getf m :neighbor-recall)) (getf m :seed-cluster-stability) (* 100 (getf m :coverage))))
    (format out "<div class='maps'>~{~A~}</div><p>Colors and cluster numbers are local to each panel. Matching colors across panels do not imply matching memberships.</p><h2>How this result was calculated</h2><p>AWRS-SMC used 24 particles over 12 steps to sample nine feature weights (0.5, 1 or 2), neighborhood size (10, 15 or 20), and minimum distance (0.05, 0.1 or 0.3). Every recipe was evaluated with Common Lisp UMAP at seeds 20260905 and 20260917, followed by DBSCAN clustering.</p><p>Quality = 0.6 × neighborhood recall + 0.3 × cluster stability across seeds + 0.1 × coverage. Recipes with fewer than two clusters receive zero quality. These are map-structure measures, not candidate-classification accuracy. The small score difference does not establish a robust advantage from two seeds alone.</p>" selected-panels)
    (format out "<details><summary>Exact recipe</summary><p>Weights in order: training duration, procedures, science, private practice, competitiveness, clinical intensity, salary, physician availability, female representation. Final two values: neighborhood size and minimum distance.</p><code>~A</code></details><p>Generated from the saved AWRS-SMC search. <a href='ref-awrs-smc-compar.html'>See the full comparison and all tested recipes.</a></p></body></html>" (awrs-html-escape (getf entry :recipe))))))
 (publication-write "ref-awrs-smc-compar.html"
  (replace-marker page "<h1>" (concatenate 'string *publication-nav* "<h1>")))
 (format t "Prepared index.html, awrs-smc.html and ref-awrs-smc-compar.html.~%"))
