(defparameter *here* (or *load-truename* *default-pathname-defaults*))
(defparameter *root* (merge-pathnames "../" *here*))

(defun read-one (relative)
  (with-open-file (in (merge-pathnames relative *root*))
    (let ((x (read in nil :eof)))
      (assert (not (eq x :eof)))
      (assert (eq (read in nil :eof) :eof))
      x)))

(defun keyed (rows) (mapcar (lambda (r) (cons (getf r :id) r)) rows))
(defun row (id table) (or (cdr (assoc id table)) (error "Missing row ~S" id)))
(defun field (id table key) (or (getf (row id table) key) (error "Missing ~S for ~S" key id)))

(defun representative-training-years (record training-document)
  (let* ((overrides (getf (getf training-document :representative-duration) :overrides))
         (override (find (getf record :id) overrides :key (lambda (item) (getf item :id)))))
    (if override (getf override :years) (getf record :minimum-total-gme-years))))

(defun mean (xs) (/ (reduce #'+ xs) (length xs)))
(defun population-sd (xs)
  (let ((m (mean xs)))
    (sqrt (/ (reduce #'+ xs :key (lambda (x) (expt (- x m) 2))) (length xs)))))
(defun zscores (xs)
  (let ((m (mean xs)) (sd (population-sd xs)))
    (assert (plusp sd))
    (mapcar (lambda (x) (/ (- x m) sd)) xs)))
(defun logs (xs base) (mapcar (lambda (x) (assert (plusp x)) (log x base)) xs))

(defun csv-string (s)
  (with-output-to-string (out)
    (write-char #\" out)
    (loop for c across s do (when (char= c #\") (write-char #\" out)) (write-char c out))
    (write-char #\" out)))
(defun csv-number (x)
  (substitute #\e #\d
              (string-downcase (string-trim '(#\Space #\Tab) (format nil "~,10G" (float x 1d0))))))
(defun csv-line (out cells)
  (loop for c in cells for first = t then nil do
    (unless first (write-char #\, out))
    (princ (etypecase c (string (csv-string c)) (symbol (string-downcase (symbol-name c))) (number (csv-number c))) out))
  (terpri out))

(let* ((training (read-one "data/specialty-training-paths.sexpr"))
       (comp (read-one "data/specialty-compensation-tasks.sexpr"))
       (science (read-one "data/specialty-scientific-activity.sexpr"))
       (private (read-one "data/private-practice.sexp"))
       (salary (read-one "data/salaries.sexp"))
       (burden (read-one "data/specialty-workforce-burden.sexp"))
       (nrmp (read-one "data/specialty-nrmp-competitiveness.sexp"))
       (sex (read-one "data/specialty-sex-distribution.sexp"))
       (procedure (read-one "data/specialty-procedure-profile.sexp"))
       (points (getf training :specialties))
       (comp-points (keyed (getf comp :specialties))) (tasks (keyed (getf comp :task-anchors)))
       (science-points (keyed (getf science :specialties))) (nih (keyed (getf science :nih-specialty-benchmarks)))
       (private-points (keyed (getf private :specialties))) (salary-points (keyed (getf salary :specialties)))
       (burden-points (keyed (getf burden :records))) (nrmp-points (keyed (getf nrmp :records)))
       (sex-points (keyed (getf sex :records)))
       (procedure-points (keyed (getf procedure :records)))
       (raw
         (mapcar
          (lambda (p)
            (let* ((id (getf p :id))
                   (task-id (field id comp-points :task-anchor-id))
                   (nih-id (field id science-points :nih-benchmark-id)))
              (list :id id :name (getf p :name)
                    :training (getf p :minimum-total-gme-years)
                    :representative-training (representative-training-years p training)
                    :work-intensity (field task-id tasks :wrvu-per-total-physician-hour)
                    :grants (field nih-id nih :grants-per-active-physician-per-year)
                    :funding (field nih-id nih :funding-thousand-usd-per-active-physician-per-year)
                    :private-practice (field id private-points :private-practice-percent)
                    :salary (field id salary-points :average-total-compensation-usd)
                    :workforce-burden (field id burden-points :physicians-per-1000-relevant-patients)
                    :competitiveness (field id nrmp-points :candidates-per-position)
                    :female-percent (field id sex-points :female-percent)
                    :procedure-profile (field id procedure-points :procedure-profile)
                    :procedure-intensity (field id procedure-points :procedure-intensity))))
          points))
       (training-z (zscores (mapcar (lambda (r) (getf r :training)) raw)))
       (work-z (zscores (logs (mapcar (lambda (r) (getf r :work-intensity)) raw) 10d0)))
       (grant-z (zscores (logs (mapcar (lambda (r) (getf r :grants)) raw) 10d0)))
       (funding-z (zscores (logs (mapcar (lambda (r) (getf r :funding)) raw) 10d0)))
       (science-unscaled (mapcar (lambda (g f) (/ (+ g f) 2d0)) grant-z funding-z))
       (science-z (zscores science-unscaled))
       (private-z (zscores (mapcar (lambda (r) (getf r :private-practice)) raw)))
       (salary-z (zscores (logs (mapcar (lambda (r) (getf r :salary)) raw) 10d0)))
       (burden-z (zscores (logs (mapcar (lambda (r) (getf r :workforce-burden)) raw) 10d0)))
       (competition-z (zscores (logs (mapcar (lambda (r) (getf r :competitiveness)) raw) 2d0)))
       (female-z (zscores (mapcar (lambda (r) (getf r :female-percent)) raw)))
       (procedure-z (zscores (mapcar (lambda (r) (getf r :procedure-intensity)) raw))))
  (assert (= 143 (length raw)))
  (with-open-file (out (merge-pathnames "examples/specialty-points-raw.csv" *root*)
                       :direction :output :if-exists :supersede :if-does-not-exist :create)
    (format out "specialty_id,specialty_name,minimum_total_gme_years,representative_total_gme_years,task_wrvu_per_total_physician_hour,nih_grants_per_active_physician_per_year,nih_funding_thousand_usd_per_active_physician_per_year,private_practice_percent,average_total_compensation_usd,physicians_per_1000_relevant_patients,candidates_per_position,female_resident_percent,procedure_profile,procedure_intensity~%")
    (dolist (r raw)
      (csv-line out (list (getf r :id) (getf r :name) (getf r :training) (getf r :representative-training) (getf r :work-intensity)
                          (getf r :grants) (getf r :funding) (getf r :private-practice) (getf r :salary)
                          (getf r :workforce-burden) (getf r :competitiveness) (getf r :female-percent)
                          (getf r :procedure-profile) (getf r :procedure-intensity)))))
  (with-open-file (out (merge-pathnames "examples/specialty-points-umap.csv" *root*)
                       :direction :output :if-exists :supersede :if-does-not-exist :create)
    (format out "specialty_id,specialty_name,training_duration_z,clinical_work_intensity_z,scientific_activity_index_z,private_practice_z,salary_z,workforce_burden_z,competitiveness_z,female_representation_z,procedure_intensity_z~%")
    (loop for r in raw for i from 0 do
      (csv-line out (list (getf r :id) (getf r :name) (nth i training-z) (nth i work-z) (nth i science-z)
                          (nth i private-z) (nth i salary-z) (nth i burden-z) (nth i competition-z)
                          (nth i female-z) (nth i procedure-z)))))
  (format t "Wrote 143 raw and 143 transformed nine-dimensional specialty points.~%"))
