;;;; Train an independent model for the best sampled AWRS-SMC alternative.
;;;; Does not write the reference application or comparison report.
(defparameter *nine-validation-main* nil)
(load (merge-pathnames "validate-nine-model.lisp" (make-pathname :name nil :type nil :defaults *load-truename*)))
(load (candidate-path "src/common-lisp-umap.lisp"))
(load (candidate-path "src/embedding-clusters.lisp"))
(defun alternative-declaration (text name json)
 (let* ((marker (format nil "const ~A=" name))
        (spaced (format nil "const ~A = " name))
        (start (let ((positions (remove nil (list (search marker text) (search spaced text))))) (if positions (reduce (function min) positions) (error "Missing declaration ~A" name))))
        (end (position #\Newline text :start start)))
  (concatenate 'string (subseq text 0 start) marker json ";" (subseq text end))))
(defun alternative-json (x) (with-output-to-string (s) (write-json x s)))
(defun alternative-cluster-name (id rows)
 (if (string= id "noise") "Unclustered"
  (let* ((members (remove-if-not (lambda (r) (equal id (getf r :cluster))) rows))
         (labels '(("long training" "short training") ("procedure-oriented" "predominantly clinical")
                   ("research-intensive" "research-light") ("private-practice-oriented" "employment-oriented")
                   ("more competitive training" "less competitive training") ("high clinical intensity" "low clinical intensity")
                   ("higher compensation" "lower compensation") ("higher physician availability" "lower physician availability")
                   ("higher female representation" "lower female representation")))
         (profile (loop for j below 9 collect (list j (/ (loop for r in members sum (nth j (getf r :input))) (length members)))))
         (ranked (sort profile #'> :key (lambda (p) (abs (second p))))))
   (format nil "Cluster ~A: ~{~A~^ + ~}" id
    (loop for (j v) in (subseq ranked 0 2) collect (nth (if (minusp v) 1 0) (nth j labels)))))))
(defun build-awrs-candidate ()
 (let* ((search (read-form-file (candidate-path "output/candidate-nine-awrs.sexp")))
        (reference (getf search :best-recipe))
        (ranked (stable-sort (copy-list (getf search :evaluations)) #'> :key (lambda (r) (getf (getf r :metrics) :quality))))
        (best (find-if (lambda (r) (not (equal (getf r :recipe) reference))) ranked))
        (recipe (getf best :recipe))
        (source (nine-observations))
        (rows (loop for id in (getf search :fit-ids) collect
                (copy-list (or (find id source :key (lambda (r) (getf r :id)) :test #'equal) (error "Missing source ~A" id)))))
        (vectors (mapcar (lambda (r) (mapcar #'* (getf r :input) (subseq recipe 0 9))) rows))
        (coordinates (cl-umap-result-coordinates
          (cl-umap-fit (make-array (list (length rows) 9) :element-type 'double-float :initial-contents vectors)
            :neighbors (nth 9 recipe) :minimum-distance (nth 10 recipe) :epochs 250 :seed 20260905 :standardize nil)))
        (z (embedding-standardized-coordinates coordinates))
        (clusters (embedding-dbscan z (embedding-knee-epsilon z 5) 5))
        (group-ids (remove-duplicates (mapcar (lambda (r) (getf r :group)) rows)))
        (question-source (getf (read-form-file (candidate-path "smc-trainer/candidate-nine-deployed.sexp")) :observations)))
  (loop for tail on rows for r = (car tail) for i from 0 do
   (let ((q (find (getf r :id) question-source :key (lambda (r) (getf r :id)) :test #'equal)))
    (unless (equal (getf r :input) (getf q :input)) (error "Questionnaire mapping is stale; rebuild the reference model."))
    (setf (getf r :question-values) (getf q :question-values) (car tail) r))
   (setf (getf r :group) (position (getf r :group) group-ids)
         (getf r :target) (list (aref coordinates i 0) (aref coordinates i 1))
         (getf r :cluster) (if (< (aref clusters i) 0) "noise" (format nil "~D" (1+ (aref clusters i))))))
  (dolist (r rows) (setf (getf r :name) (alternative-cluster-name (getf r :cluster) rows)))
  (candidate-write (candidate-path "smc-trainer/corpus/candidate-awrs-supervised.sexp")
   (list :format :candidate-supervised-corpus :version 1 :recipe recipe :seed 20260905 :epochs 250 :records rows))
  (let ((correct 0) (position-correct 0) (nearest 0) (partial 0) folds)
   (dotimes (fold 5)
    (let* ((train (remove-if (lambda (r) (= (mod (getf r :group) 5) fold)) rows))
           (test (set-difference rows train)) (choice (nine-tune train))
           (model (nine-fit train (first choice) (second choice))) (m (nine-measure model train test))
           (base (nine-baseline (append (mapcar (lambda (r) (append (list :split :train) r)) train)
                                       (mapcar (lambda (r) (append (list :split :validation) r)) test))))
           (p (count-if (lambda (r) (equal (getf r :cluster) (nine-predict-partial model (getf r :input) train))) test)))
     (incf correct (getf m :correct)) (incf position-correct (getf m :coordinate-cluster-correct))
     (incf nearest (getf base :correct)) (incf partial p)
     (push (list :fold fold :selected choice :metrics m :training-ids (mapcar (lambda (r) (getf r :id)) train)
                 :validation-ids (mapcar (lambda (r) (getf r :id)) test)) folds)))
   (let* ((choice (nine-tune rows))
          (evaluation (list :total (length rows) :correct correct :coordinate-cluster-correct position-correct
                           :nearest-neighbor-correct nearest :five-known-correct partial
                           :scope "Nested grouped mapping validation within the fixed 117-record alternative atlas; not independent validation of the AWRS search or career outcomes."))
          (artifact (append (nine-fit rows (first choice) (second choice))
            (list :format :candidate-awrs-deployed :version 1 :feature-schema (mapcar #'symbol-name *nine-fields*)
                  :observations rows :evaluation evaluation :selected choice :recipe recipe :seed 20260905 :epochs 250)))
          (fixtures (mapcar (lambda (r) (list :input (getf r :input) :expected (nine-predict artifact (getf r :input)))) rows))
          (manifest (read-form-file (candidate-path "specialty-problem.sexpr")))
          (all-page-rows (read-dataset (candidate-path "output/specialty-umap-embedding.csv") (getf manifest :data)))
          (page-rows (loop for r in rows collect
            (let ((p (copy-list (find (getf r :id) all-page-rows :key (lambda (p) (getf p :specialty-id)) :test #'equal))))
             (setf (getf p :x) (first (getf r :target)) (getf p :y) (second (getf r :target))
                   (getf p :cluster-id) (getf r :cluster) (getf p :cluster-name) (getf r :name)) p)))
          (page (file-text (candidate-path "output/specialty-candidate.html"))))
    (candidate-write (candidate-path "smc-trainer/candidate-awrs-deployed.sexp") artifact)
    (candidate-write (candidate-path "output/candidate-awrs-validation.sexp") (append evaluation (list :folds (nreverse folds))))
    (with-open-file (s (candidate-path "output/candidate-awrs-model.json") :direction :output :if-exists :supersede)
     (write-json (list :artifact artifact :fixtures fixtures) s))
    (setf (getf manifest :title) "Medical specialties: AWRS-SMC alternative")
    (setf page (alternative-declaration page "problem" (alternative-json manifest))
          page (alternative-declaration page "rows" (alternative-json page-rows))
          page (alternative-declaration page "nineArtifact" (alternative-json artifact))
          page (replace-marker page "AWRS-SMC found no better map recipe in the tested search." "This validates the separate best-sampled-alternative model on 117 specialties. Its map is fixed before the folds; these numbers do not independently validate the search.")
          page (replace-marker page "<main id=\"app\">"
            "<main id=\"app\"><nav><a href='index.html'>Reference</a> · <a href='awrs-smc.html'>AWRS-SMC alternative</a> · <a href='ref-awrs-smc-compar.html'>Comparison</a></nav><p>Best sampled alternative · 117 search specialties · seed 20260905 · 250 epochs. This uses its own trained model, coordinates and clusters. The comparison page shows both search seeds.</p>"))
    ;; Draw unclustered atlas records as plus signs, with the same point tooltips.
    (setf page (replace-marker page ".join(\"circle\")
          .attr(\"class\", \"point-halo\")"
     ".join(\"path\")
          .attr(\"d\", row => String(row.cluster_id) === 'noise' ? 'M-6 0H6 M0-6V6' : 'M-5,0 a5,5 0 1,0 10,0 a5,5 0 1,0 -10,0')
          .attr(\"transform\", row => `translate(${x(row.x)},${y(row.y)})`)
          .attr(\"stroke\", row => String(row.cluster_id) === 'noise' ? '#222' : 'none')
          .attr(\"stroke-width\", 2)
          .attr(\"class\", \"point-halo\")"))
    (with-open-file (s (candidate-path "awrs-smc.html") :direction :output :if-exists :supersede) (write-string page s))
    (format t "AWRS application trained: label accuracy ~D/~D; coordinate cluster recovery ~D/~D. Wrote awrs-smc.html.~%" correct (length rows) position-correct (length rows))))))
(build-awrs-candidate)
