;;;; Reconstruct the saved search recipes as a standalone HTML comparison.
(defparameter *nine-evaluate-main* nil)
(load (merge-pathnames "evaluate-nine-map.lisp" (make-pathname :name nil :type nil :defaults *load-truename*)))
(load (candidate-path "src/common-lisp-umap.lisp"))
(load (candidate-path "src/embedding-clusters.lisp"))
(defun awrs-html-escape (value)
 (with-output-to-string (s) (loop for c across (princ-to-string value) do
  (write-string (case c (#\& "&amp;") (#\< "&lt;") (#\> "&gt;") (#\" "&quot;") (t (string c))) s))))
(defun awrs-html-panel (out rows recipe seed title)
 (let* ((vectors (mapcar (lambda (r) (mapcar #'* (getf r :input) (subseq recipe 0 9))) rows))
        (input (make-array (list (length rows) 9) :element-type 'double-float :initial-contents vectors))
        (coordinates (cl-umap-result-coordinates (cl-umap-fit input :neighbors (nth 9 recipe) :minimum-distance (nth 10 recipe) :epochs 250 :seed seed :standardize nil)))
        (z (embedding-standardized-coordinates coordinates))
        (assignments (embedding-dbscan z (embedding-knee-epsilon z 5) 5))
        (xmin (loop for i below (length rows) minimize (aref coordinates i 0)))
        (xmax (loop for i below (length rows) maximize (aref coordinates i 0)))
        (ymin (loop for i below (length rows) minimize (aref coordinates i 1)))
        (ymax (loop for i below (length rows) maximize (aref coordinates i 1)))
        (colors '("#4e79a7" "#f28e2b" "#e15759" "#76b7b2" "#59a14f" "#edc949" "#af7aa1" "#ff9da7" "#9c755f" "#bab0ac")))
  (format out "<section><h2>~A</h2><p>Seed ~D · ~D clusters · ~D unclustered</p><svg viewBox='0 0 560 400' role='img' aria-label='~A'><rect x='20' y='15' width='520' height='365' fill='#fafafa' stroke='#ddd'/>" title seed (1+ (reduce #'max assignments)) (count -1 assignments) title)
  (loop for r in rows for i from 0 for cluster = (aref assignments i) do
   (let ((x (+ 40 (* 480 (/ (- (aref coordinates i 0) xmin) (max 1d-9 (- xmax xmin))))))
         (y (- 360 (* 325 (/ (- (aref coordinates i 1) ymin) (max 1d-9 (- ymax ymin)))))))
    (if (< cluster 0)
        (format out "<path class='unclustered' transform='translate(~,3F ~,3F)' d='M-6 0H6 M0-6V6' fill='none' stroke='#222' stroke-width='2' stroke-linecap='round'>" x y)
        (format out "<circle cx='~,3F' cy='~,3F' r='5' fill='~A' stroke='white' stroke-width='0.7'>" x y (nth (mod cluster (length colors)) colors)))
    (format out "<title>~A — ~A; x=~,3F, y=~,3F</title>~A"
     (awrs-html-escape (getf r :id)) (if (< cluster 0) "Unclustered" (format nil "Cluster ~D" (1+ cluster)))
     (aref coordinates i 0) (aref coordinates i 1) (if (< cluster 0) "</path>" "</circle>"))))
  (format out "</svg></section>")))
(let* ((result (read-form-file (candidate-path "output/candidate-nine-awrs.sexp")))
       (rows (remove-if-not (lambda (r) (member (getf r :id) (getf result :fit-ids) :test #'equal)) (nine-observations)))
       (best (getf result :best-recipe))
       (ranked (sort (copy-list (getf result :evaluations)) #'> :key (lambda (r) (getf (getf r :metrics) :quality))))
       (alternative (find-if (lambda (r) (not (equal (getf r :recipe) best))) ranked))
       (output (candidate-path "output/specialty-awrs-result.html")))
 (unless (= (length rows) (length (getf result :fit-ids))) (error "Search records changed."))
 (with-open-file (out output :direction :output :if-exists :supersede)
  (format out "<!doctype html><html lang='en'><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Specialty UMAP — AWRS-SMC result</title><style>body{font:15px system-ui;margin:24px auto;padding:0 20px;max-width:1200px;color:#20242b}h1{font-size:24px}h2{font-size:18px}p{line-height:1.5}.maps{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:20px}section{border:1px solid #ddd;border-radius:10px;padding:14px}svg{width:100%;height:auto}circle:hover{r:8;stroke:#111}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:8px;border-bottom:1px solid #ddd}code{overflow-wrap:anywhere}.table{overflow:auto}</style><h1>AWRS-SMC: saved search result</h1><p>The reference recipe won. Below are its maps and the strongest sampled alternative, reconstructed with the exact search settings: <strong>~D training specialties, 250 epochs, two seeds</strong>. These are search-sample maps, not the deployed 143-point atlas. Unclustered points are marked with a dark plus (+). Hover over a point for its specialty.</p><p>Cluster numbers and colors are local to each panel; matching colors do not imply matching membership. Map rotations and positions can differ between runs.</p><div class='table'><table><tr><th>Recipe</th><th>Quality</th><th>Neighbor recall</th><th>Two-seed stability</th><th>Coverage</th></tr>" (length rows))
  (loop for label in '("Reference (winner)" "Best sampled alternative")
        for entry in (list (list :metrics (getf result :best)) alternative)
        for m = (getf entry :metrics) do
    (format out "<tr><td>~A</td><td>~,4F</td><td>~,1F%</td><td>~,4F</td><td>~,1F%</td></tr>" label (getf m :quality) (* 100 (getf m :neighbor-recall)) (getf m :seed-cluster-stability) (* 100 (getf m :coverage))))
  (format out "</table></div><p>These scores measure map structure, not candidate-classification accuracy.</p><div class='maps'>")
  (dolist (seed '(20260905 20260917)) (awrs-html-panel out rows best seed "Reference recipe — search winner"))
  (dolist (seed '(20260905 20260917)) (awrs-html-panel out rows (getf alternative :recipe) seed "Best sampled alternative"))
  (format out "</div><details><summary>All 25 evaluated recipes and weights</summary><p>Weights: training, procedures, science, private practice, competitiveness, clinical intensity, salary, physician availability, female representation. Final two values: neighbors and minimum distance.</p><div class='table'><table><tr><th>Rank</th><th>Recipe</th><th>Quality</th></tr>")
  (loop for entry in ranked for rank from 1 do (format out "<tr><td>~D</td><td><code>~A</code></td><td>~,4F</td></tr>" rank (awrs-html-escape (getf entry :recipe)) (getf (getf entry :metrics) :quality)))
  (format out "</table></div></details><p>24 AWRS-SMC particles · 12 steps · 24 alternatives plus the reference. No alternative replaced the current map.</p></html>"))
 (format t "Wrote ~A~%" output))
