;;;; Deploy the selected nine-input model, retaining the current reference atlas.
(defparameter *nine-validation-main* nil)
(load (merge-pathnames "validate-nine-model.lisp" (make-pathname :name nil :type nil :defaults *load-truename*)))
(defun nine-question-records (rows)
 (let* ((*read-default-float-format* 'double-float)
        (raw (read-csv-records (candidate-path "examples/specialty-points-raw.csv"))))
  (mapcar (lambda (r)
   (let* ((a (find (getf r :id) raw :key (lambda (x) (getf x :specialty-id)) :test #'equal)) (v (getf r :input)))
    (append r (list :question-values
     (list (getf a :minimum-total-gme-years) (getf a :procedure-intensity) (nth 2 v)
           (getf a :private-practice-percent) (nth 4 v) (nth 5 v)
           (/ (getf a :average-total-compensation-usd) 1000d0) (nth 7 v) (getf a :female-resident-percent)))))) rows)))
(defun nine-json (value) (with-output-to-string (s) (write-json value s)))
(defun nine-build-page ()
 (let* ((rows (nine-question-records (nine-observations)))
        (selected (read-form-file (candidate-path "smc-trainer/candidate-nine-rbf.sexp")))
        (cv (read-form-file (candidate-path "output/candidate-nine-cross-validation.sexp")))
        (awrs (read-form-file (candidate-path "output/candidate-nine-awrs.sexp")))
        (recipe (getf selected :selected))
        (artifact (append (nine-fit rows (first recipe) (second recipe))
          (list :format :candidate-nine-deployed :version 1 :observations rows
                :feature-schema (mapcar #'symbol-name *nine-fields*)
                :evaluation (loop for key in '(:total :correct :coordinate-cluster-correct :five-known-correct :nearest-neighbor-correct :scope) append (list key (getf cv key)))
                :legacy-holdout (loop for key in '(:correct :total :cluster-agreement :coordinate-cluster-correct :coordinate-rmse) append (list key (getf (getf selected :evaluation) key)))
                :training-policy "All 143 atlas rows refitted after grouped cross-validation; validation figures are out-of-fold, not training accuracy."
                :atlas-decision (list :selected :original :awrs-best (getf awrs :best-recipe)))))
        (fixtures (mapcar (lambda (r) (list :input (getf r :input) :expected (nine-predict artifact (getf r :input)))) rows)))
  ;; Fail closed if training or validation artifacts belong to different source rows.
  (unless (equal (nine-observations) (getf selected :observations)) (error "Source data changed; rerun the nine-feature training pipeline."))
  (unless (= (getf cv :total) (length rows)) (error "Validation row count differs"))
  (candidate-write (candidate-path "smc-trainer/candidate-nine-deployed.sexp") artifact)
  (with-open-file (s (candidate-path "output/candidate-nine-model.json") :direction :output :if-exists :supersede)
   (write-json (list :artifact artifact :fixtures fixtures) s))
  (build-umap-html (candidate-path "specialty-problem.sexpr") (candidate-path "output/specialty-candidate.html"))
  (let* ((page (file-text (candidate-path "output/specialty-candidate.html")))
         (code (concatenate 'string (file-text (candidate-path "src/candidate-nine-engine.js"))
                (format nil "~%const nineArtifact=~A;~%" (nine-json artifact))
                (file-text (candidate-path "src/candidate-nine-ui.js"))))
         (css "#candidate-panel{margin:14px 0;padding:12px;border:1px solid #ccc;border-radius:6px}#candidate-panel summary{cursor:pointer;font-weight:600}.candidate-fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.candidate-fields fieldset{border:1px solid #ddd;min-width:0}.candidate-fields input[type=number]{width:65px;margin:5px}.candidate-fields small{display:block;color:#555}#candidate-form button{margin:10px 10px 0 0}#candidate-quality{font-size:12px;color:#555}"))
   (setf page (replace-marker page "</style>" (concatenate 'string css "</style>"))
         page (replace-marker page "      <svg role=\"img\"></svg>" (concatenate 'string (file-text (candidate-path "src/candidate-nine-panel.html")) "<svg role=\"img\"></svg>"))
         page (replace-marker page "      select.addEventListener(\"change\", draw);" (concatenate 'string code "      select.addEventListener(\"change\", draw);"))
         page (replace-marker page "        root.querySelector(\".ramp\").style.background" "        drawNineOverlay(x, y);
        root.querySelector(\".ramp\").style.background")
         page (replace-marker page "      layoutSelect.add(new Option(\"Recompute with umap-js\", \"umap-js\"));" "      layoutSelect.disabled = true; // Trained predictions use this reference atlas."))
   (with-open-file (s (candidate-path "output/specialty-candidate.html") :direction :output :if-exists :supersede) (write-string page s)))))
(nine-build-page)
