;;;; Compare five- and nine-feature predictors on the identical grouped holdout.
(defparameter *candidate-run-main* nil)
(load (merge-pathnames "train-candidate-map.lisp" (make-pathname :name nil :type nil :defaults *load-truename*)))
(defparameter *nine-fields* '(:training-duration-z :procedure-intensity-z :scientific-activity-index-z :private-practice-z :competitiveness-z :clinical-work-intensity-z :salary-z :workforce-burden-z :female-representation-z))
(defun nine-observations ()
 (let* ((*read-default-float-format* 'double-float)
        (atlas (read-csv-records (candidate-path "output/specialty-umap-embedding.csv"))))
  (loop for r in (candidate-split (candidate-observations))
        for a = (find (getf r :id) atlas :key (lambda (x) (getf x :specialty-id)) :test #'equal)
        collect (let ((copy (copy-list r)))
                  (setf (getf copy :five-input) (getf r :input)
                        (getf copy :input) (mapcar (lambda (f) (getf a f)) *nine-fields*))
                  copy))))
(defun nine-baseline (rows &optional (key :input))
 (let* ((train (remove :validation rows :key (lambda (r) (getf r :split))))
        (test (remove :train rows :key (lambda (r) (getf r :split))))
        (stats (candidate-stats (mapcar (lambda (r) (getf r key)) train)))
        (correct 0))
  (dolist (r test)
   (let ((nearest (first (sort (copy-list train) #'< :key (lambda (s) (candidate-distance (candidate-normalize (getf r key) stats) (candidate-normalize (getf s key) stats)))))))
    (when (equal (getf r :cluster) (getf nearest :cluster)) (incf correct))))
  (list :correct correct :total (length test) :agreement (/ correct (float (length test) 1d0)))))
(defvar *nine-evaluate-main* t)
(when *nine-evaluate-main*
 (let* ((rows (nine-observations)) (training (remove :validation rows :key (lambda (r) (getf r :split))))
        (inputs (candidate-stats (mapcar (lambda (r) (getf r :input)) training)))
        (targets (candidate-stats (mapcar (lambda (r) (getf r :target)) training)))
        (corpus (candidate-path "smc-trainer/corpus/candidate-nine.sexp")))
  (format t "Five nearest neighbor ~S~%Nine nearest neighbor ~S~%" (nine-baseline rows :five-input) (nine-baseline rows))
  (let ((*candidate-fields* *nine-fields*)) (candidate-write corpus (candidate-corpus rows inputs targets)))
  (multiple-value-bind (model report) (train-parametric-source (parametric-open-corpus-source corpus) :epochs 200)
   (let ((evaluation (candidate-evaluate model rows inputs targets)))
    (candidate-write (candidate-path "smc-trainer/candidate-nine-transformer.sexp")
     (list :model (parametric-model-form model) :preprocessing inputs :target-preprocessing targets :evaluation evaluation :training-report report))
    (format t "Nine Transformer ~S~%" evaluation)))))
