;;;; AWRS-SMC atlas experiment: all nine features, training partition only.
(defparameter *nine-evaluate-main* nil)
(load (merge-pathnames "evaluate-nine-map.lisp" (make-pathname :name nil :type nil :defaults *load-truename*)))
(load (candidate-path "awrs-smc/smc.lisp"))
(load (candidate-path "src/common-lisp-umap.lisp"))
(load (candidate-path "src/embedding-clusters.lisp"))
(load (candidate-path "src/v-measure.lisp"))
(defun atlas-array (vectors)
 (make-array (list (length vectors) (length (first vectors))) :element-type 'double-float :initial-contents vectors))
(defun atlas-clusters (coordinates)
 (let* ((z (embedding-standardized-coordinates coordinates)) (epsilon (embedding-knee-epsilon z 5)))
  (embedding-dbscan z epsilon 5)))
(defun atlas-neighbors (vectors index)
 (subseq (sort (loop for v in vectors for j from 0 unless (= j index) collect j) #'<
  :key (lambda (j) (candidate-distance (nth index vectors) (nth j vectors)))) 0 5))
(defun atlas-recall (original coordinates)
 (let ((mapped (loop for i below (array-dimension coordinates 0) collect (list (aref coordinates i 0) (aref coordinates i 1)))))
  (/ (loop for i below (length original) sum (/ (length (intersection (atlas-neighbors original i) (atlas-neighbors mapped i))) 5d0)) (length original))))
(defun atlas-quality (rows recipe)
 (let* ((vectors (mapcar (lambda (r) (getf r :input)) rows))
        (weighted (mapcar (lambda (v) (mapcar #'* v (subseq recipe 0 9))) vectors))
        (a (cl-umap-result-coordinates (cl-umap-fit (atlas-array weighted) :neighbors (nth 9 recipe) :minimum-distance (nth 10 recipe) :epochs 250 :seed 20260905 :standardize nil)))
        (b (cl-umap-result-coordinates (cl-umap-fit (atlas-array weighted) :neighbors (nth 9 recipe) :minimum-distance (nth 10 recipe) :epochs 250 :seed 20260917 :standardize nil)))
        (ca (atlas-clusters a)) (cb (atlas-clusters b))
        (recall (/ (+ (atlas-recall vectors a) (atlas-recall vectors b)) 2d0))
        (stability (umap-v-measure-result-v-measure (umap-v-measure-from-vectors ca cb)))
        (coverage (/ (+ (count-if (lambda (x) (>= x 0)) ca) (count-if (lambda (x) (>= x 0)) cb)) (* 2d0 (length rows))))
        (clusters (1+ (reduce #'max ca))))
  (list :quality (if (< clusters 2) 0d0 (+ (* .6d0 recall) (* .3d0 stability) (* .1d0 coverage)))
        :neighbor-recall recall :seed-cluster-stability stability :coverage coverage :cluster-count clusters)))
(let* ((rows (remove :validation (nine-observations) :key (lambda (r) (getf r :split))))
       (cache (make-hash-table :test #'equal))
       (default (append (make-list 9 :initial-element 1d0) '(15 0.1d0))))
 (labels ((evaluate-recipe (recipe) (or (gethash recipe cache)
          (setf (gethash (copy-list recipe) cache) (atlas-quality rows recipe)))))
  (let* ((baseline (evaluate-recipe default))
         (result (awrs-smc:run-awrs-smc
          (lambda (prefix)
           (let ((options (cond ((< (length prefix) 9) '(0.5d0 1d0 2d0)) ((= (length prefix) 9) '(10 15 20)) ((= (length prefix) 10) '(0.05d0 0.1d0 0.3d0)) (t '(:eos)))))
            (mapcar (lambda (x) (cons x (/ 1d0 (length options)))) options)))
          (lambda (prefix choice) (if (eq choice :eos) (= (length prefix) 11) (< (length prefix) 11)))
          :particle-count 24 :maximum-steps 12 :resampling-threshold .65d0 :seed 20260908
          :terminal-potential-function (lambda (recipe) (exp (* 12d0 (getf (evaluate-recipe recipe) :quality))))))
         (best default) (quality (getf baseline :quality)))
   (maphash (lambda (recipe metrics) (when (> (getf metrics :quality) quality) (setf best recipe quality (getf metrics :quality)))) cache)
   (candidate-write (candidate-path "output/candidate-nine-awrs.sexp")
    (list :format :candidate-nine-atlas-search :version 1 :fit-ids (mapcar (lambda (r) (getf r :id)) rows)
          :objective "0.6 neighbor recall + 0.3 two-seed cluster stability + 0.1 coverage; reject fewer than two clusters"
          :settings '(:particles 24 :steps 12 :epochs 250 :umap-seeds (20260905 20260917) :smc-seed 20260908)
          :baseline baseline :best-recipe best :best (evaluate-recipe best)
          :evaluations (loop for recipe being the hash-keys of cache using (hash-value value) collect (list :recipe recipe :metrics value))
          :telemetry (awrs-smc:awrs-smc-result-telemetry result)))
   (format t "AWRS-SMC: ~D map recipes, each evaluated at two seeds.~%Default ~S~%Best ~S: ~S~%" (hash-table-count cache) baseline best (evaluate-recipe best)))))
