;;;; Tune within the old training partition, then evaluate the frozen holdout once.
(defparameter *nine-evaluate-main* nil)
(load (merge-pathnames "evaluate-nine-map.lisp" (make-pathname :name nil :type nil :defaults *load-truename*)))
(load (candidate-path "smc-trainer/rbf.lisp"))
(defun nine-fit (rows width ridge)
 (let* ((inputs (candidate-stats (mapcar (lambda (r) (getf r :input)) rows)))
        (targets (candidate-stats (mapcar (lambda (r) (getf r :target)) rows)))
        (classes (sort (remove-duplicates (mapcar (lambda (r) (getf r :cluster)) rows) :test #'equal) #'string<))
        (model (rbf-fit (mapcar (lambda (r) (candidate-normalize (getf r :input) inputs)) rows)
               (mapcar (lambda (r) (append (candidate-normalize (getf r :target) targets)
                 (mapcar (lambda (c) (if (equal c (getf r :cluster)) 1d0 0d0)) classes))) rows) width ridge)))
  (list :model model :preprocessing inputs :target-preprocessing targets :classes classes)))
(defun nine-predict (artifact input)
 (let* ((values (rbf-predict (getf artifact :model) (candidate-normalize input (getf artifact :preprocessing))))
        (scores (cddr values)) (index (position (reduce #'max scores) scores)))
  (list :point (candidate-denormalize (subseq values 0 2) (getf artifact :target-preprocessing))
        :cluster (nth index (getf artifact :classes)) :scores scores)))
(defun nine-measure (artifact training test)
 (let ((correct 0) (position-correct 0) (sse 0d0) predictions)
  (dolist (r test)
   (let* ((prediction (nine-predict artifact (getf r :input)))
          (near (first (sort (copy-list training) #'< :key (lambda (s) (candidate-distance (getf prediction :point) (getf s :target)))))))
    (when (equal (getf prediction :cluster) (getf r :cluster)) (incf correct))
    (when (equal (getf near :cluster) (getf r :cluster)) (incf position-correct))
    (incf sse (candidate-distance (getf prediction :point) (getf r :target)))
    (push (list :id (getf r :id) :actual (getf r :cluster) :predicted (getf prediction :cluster) :point (getf prediction :point)) predictions)))
  (list :correct correct :total (length test) :cluster-agreement (/ correct (float (length test) 1d0))
        :coordinate-cluster-correct position-correct :coordinate-rmse (sqrt (/ sse (* 2 (length test))))
        :predictions (nreverse predictions))))
(defvar *nine-rbf-main* t)
(when *nine-rbf-main*
 (let* ((rows (nine-observations)) (train (remove :validation rows :key (lambda (r) (getf r :split))))
        (test (remove :train rows :key (lambda (r) (getf r :split))))
        (inner-train (remove-if (lambda (r) (zerop (mod (getf r :group) 4))) train))
        (inner-test (set-difference train inner-train)) (best nil) (best-score -1d10) results)
  (candidate-write (candidate-path "smc-trainer/corpus/candidate-nine-supervised.sexp")
   (list :format :candidate-supervised-corpus :version 1 :feature-schema (mapcar #'symbol-name *nine-fields*)
         :source "output/specialty-umap-embedding.csv" :records rows))
  (dolist (width '(0.3d0 0.5d0 0.8d0 1.2d0 2d0 3d0))
   (dolist (ridge '(0.001d0 0.01d0 0.1d0))
    (let* ((a (nine-fit inner-train width ridge)) (metrics (nine-measure a inner-train inner-test))
           (score (- (getf metrics :cluster-agreement) (* 0.01d0 (getf metrics :coordinate-rmse)))))
     (push (list :width width :ridge ridge :metrics metrics) results)
     (when (> score best-score) (setf best-score score best (list width ridge))))))
  (let* ((artifact (nine-fit train (first best) (second best))) (metrics (nine-measure artifact train test)))
   (setf artifact (append artifact (list :format :candidate-nine-rbf :version 1 :feature-schema (mapcar #'symbol-name *nine-fields*)
                    :observations rows :evaluation metrics :tuning results :selected best :training-ids (mapcar (lambda (r) (getf r :id)) train))))
   (candidate-write (candidate-path "smc-trainer/candidate-nine-rbf.sexp") artifact)
   (format t "Selected ~S using ~D inner training, ~D inner validation. Outer evaluation: ~S~%" best (length inner-train) (length inner-test) (subseq metrics 0 10)))))
