;;;; Validate the specialty point universe and first numeric feature. SBCL only.

(defun read-safe-form (path)
  (with-open-file (stream path)
    (let ((*read-eval* nil))
      (let ((form (read stream nil :eof)))
        (when (eq form :eof) (error "Empty file: ~A" path))
        (unless (eq (read stream nil :eof) :eof)
          (error "More than one top-level form: ~A" path))
        form))))

(defun positive-year-list-p (value)
  (and (consp value) (every (lambda (x) (and (integerp x) (plusp x))) value)))

(let* ((path (or (second sb-ext:*posix-argv*)
                 "data/specialty-training-paths.sexpr"))
       (document (read-safe-form path))
       (records (getf document :specialties))
       (representative (getf document :representative-duration))
       (seen (make-hash-table :test #'eq)))
  (unless (eq (getf document :format) :specialty-training-paths)
    (error "Unexpected format"))
  (unless records (error "No specialty records"))
  (dolist (record records)
    (let ((id (getf record :id))
          (prior (getf record :prior-years))
          (program (getf record :program-years))
          (total (getf record :minimum-total-gme-years)))
      (unless (keywordp id) (error "Invalid ID in ~S" record))
      (when (gethash id seen) (error "Duplicate ID: ~S" id))
      (setf (gethash id seen) t)
      (unless (and (listp prior)
                   (every (lambda (x) (and (integerp x) (not (minusp x)))) prior))
        (error "Invalid prior years for ~S" id))
      (unless (positive-year-list-p program)
        (error "Invalid program years for ~S" id))
      (unless (and (integerp total) (plusp total))
        (error "Invalid total years for ~S" id))
      (let ((paths (getf record :paths)))
        (unless paths (error "No training path for ~S" id))
        (let ((path-minimum
                (apply #'min
                       (mapcar (lambda (path)
                                 (reduce #'+ path :key #'third))
                               paths))))
          (unless (= total path-minimum)
            (error "Total ~D disagrees with shortest path ~D for ~S"
                   total path-minimum id))))))
  (dolist (required '(:internal-medicine :cardiology
                      :cardiac-electrophysiology :interventional-cardiology))
    (unless (gethash required seen) (error "Missing required point: ~S" required)))
  (let ((override-seen (make-hash-table :test #'eq)))
    (dolist (override (getf representative :overrides))
      (let ((id (getf override :id)) (years (getf override :years)))
        (unless (gethash id seen) (error "Representative override has unknown ID: ~S" id))
        (when (gethash id override-seen) (error "Duplicate representative override: ~S" id))
        (setf (gethash id override-seen) t)
        (unless (and (integerp years) (plusp years))
          (error "Invalid representative duration for ~S" id))))
    (unless (= 6 (getf (find :medical-oncology (getf representative :overrides)
                             :key (lambda (item) (getf item :id))) :years))
      (error "Medical oncology representative duration must be six years.")))
  (format t "PASS specialty-training-paths: ~D unique points; representative durations audited~%"
          (length records)))
