(defparameter *here* (or *load-truename* *default-pathname-defaults*))
(defparameter *root* (merge-pathnames "../" *here*))
(defun lines (p) (with-open-file (i p) (loop for line = (read-line i nil nil) while line collect line)))
(defun columns (s)
  (let ((n 1) (quoted nil) (i 0))
    (loop while (< i (length s)) do
      (let ((c (char s i)))
        (cond ((char= c #\")
               (if (and quoted (< (1+ i) (length s)) (char= (char s (1+ i)) #\"))
                   (incf i)
                   (setf quoted (not quoted))))
              ((and (char= c #\,) (not quoted)) (incf n))))
      (incf i))
    (assert (not quoted))
    n))
(let ((raw (lines (merge-pathnames "examples/specialty-points-raw.csv" *root*)))
      (umap (lines (merge-pathnames "examples/specialty-points-umap.csv" *root*))))
  (assert (= 144 (length raw) (length umap)))
  (assert (= 11 (columns (first raw))))
  (assert (= 10 (columns (first umap))))
  (assert (every (lambda (s) (= 11 (columns s))) (rest raw)))
  (assert (every (lambda (s) (= 10 (columns s))) (rest umap)))
  (assert (search "specialty_id,specialty_name" (first raw)))
  (assert (search "scientific_activity_index_z" (first umap)))
  (assert (search "female_representation_z" (first umap)))
  (format t "PASS: two CSV files; 143 ordered points; raw operands and eight UMAP coordinates present.~%"))
