(defparameter *here* (or *load-truename* *default-pathname-defaults*))
(defparameter *root* (merge-pathnames "../" *here*))
(defun load-one (path) (with-open-file (in path) (let ((x (read in nil :eof))) (assert (not (eq x :eof))) (assert (eq (read in nil :eof) :eof)) x)))
(let* ((training (load-one (merge-pathnames "data/specialty-training-paths.sexpr" *root*)))
       (data (load-one (merge-pathnames "data/specialty-workforce-burden.sexp" *root*)))
       (points (getf training :specialties)) (records (getf data :records)))
  (assert (= 143 (length points) (length records)))
  (assert (equal (mapcar (lambda (x) (getf x :id)) points) (mapcar (lambda (x) (getf x :id)) records)))
  (dolist (r records)
    (assert (plusp (getf r :physician-count)))
    (assert (plusp (getf r :relevant-patient-count)))
    (assert (< (abs (- (getf r :physicians-per-1000-relevant-patients)
                       (/ (* 1000.0d0 (getf r :physician-count)) (getf r :relevant-patient-count)))) 1d-10))
    (assert (getf r :umap-use)))
  (let ((heme (find :hematology-and-medical-oncology records :key (lambda (x) (getf x :id))))
        (onc (find :medical-oncology records :key (lambda (x) (getf x :id)))))
    (assert (= 16715 (getf heme :physician-count)))
    (assert (= 20000000 (getf heme :relevant-patient-count)))
    (assert (< (abs (- (getf heme :physicians-per-1000-relevant-patients) 0.83575d0)) 1d-10))
    (assert (= 4778 (getf onc :physician-count)))
    (assert (= 20000000 (getf onc :relevant-patient-count)))
    (assert (< (abs (- (getf onc :physicians-per-1000-relevant-patients) 0.2389d0)) 1d-10))
    (assert (not (= (getf heme :physicians-per-1000-relevant-patients)
                    (getf onc :physicians-per-1000-relevant-patients)))))
  (let ((endo (find :endocrinology-diabetes-and-metabolism records :key (lambda (x) (getf x :id)))))
    (assert (< (abs (- (getf endo :physicians-per-1000-relevant-patients) 0.2d0)) 1d-10)))
  (format t "PASS: ~D points; arithmetic valid; combined oncology need and separate salary identities preserved; checks reproduce 0.83575, 0.2389, and 0.2.~%" (length records)))
