#!/usr/bin/env sbcl --script

;;; Dependency-free structural and arithmetic validation.

(defparameter *root* (make-pathname :name nil :type nil :defaults *load-truename*))

(defun read-one (relative)
  (with-open-file (stream (merge-pathnames relative *root*) :direction :input)
    (read stream)))

(defun ensure (condition control &rest arguments)
  (unless condition (apply #'error control arguments)))

(defun unique-p (items)
  (= (length items) (length (remove-duplicates items))))

(defun close-enough-p (a b)
  (< (abs (- a b)) 0.00011))

(let* ((training (read-one "../data/specialty-training-paths.sexpr"))
       (data (read-one "../data/specialty-compensation-tasks.sexpr"))
       (points (getf training :specialties))
       (records (getf data :specialties))
       (benchmarks (getf data :benchmarks))
       (anchors (getf data :task-anchors))
       (point-ids (mapcar (lambda (x) (getf x :id)) points))
       (record-ids (mapcar (lambda (x) (getf x :id)) records))
       (benchmark-ids (mapcar (lambda (x) (getf x :id)) benchmarks))
       (anchor-ids (mapcar (lambda (x) (getf x :id)) anchors)))
  (ensure (unique-p record-ids) "Duplicate specialty feature ID")
  (ensure (equal point-ids record-ids) "Feature IDs/order differ from training point universe")
  (ensure (unique-p benchmark-ids) "Duplicate benchmark ID")
  (ensure (unique-p anchor-ids) "Duplicate task-anchor ID")
  (dolist (record records)
    (ensure (member (getf record :benchmark-id) benchmark-ids)
            "Unknown benchmark ~S for ~S" (getf record :benchmark-id) (getf record :id))
    (ensure (member (getf record :task-anchor-id) anchor-ids)
            "Unknown anchor ~S for ~S" (getf record :task-anchor-id) (getf record :id))
    (ensure (eq (getf record :benchmark-imputed-p)
                (eq (getf record :benchmark-match) :nearest-available))
            "Benchmark imputation flag mismatch for ~S" (getf record :id))
    (ensure (eq (getf record :task-imputed-p)
                (eq (getf record :task-match) :nearest-available))
            "Task imputation flag mismatch for ~S" (getf record :id)))
  (let ((combined (find :hematology-and-medical-oncology records :key (lambda (x) (getf x :id))))
        (oncology (find :medical-oncology records :key (lambda (x) (getf x :id)))))
    (ensure combined "Missing hematology/oncology point")
    (ensure oncology "Missing oncology-only point")
    (ensure (not (eq (getf combined :task-anchor-id) (getf oncology :task-anchor-id)))
            "Oncology-only and hematology/oncology task identities were collapsed")
    (ensure (eq :nearest-available (getf oncology :benchmark-match))
            "Oncology-only must not be called a direct hematology/oncology benchmark"))
  (dolist (anchor anchors)
    (let ((wrvu (getf anchor :work-rvu))
          (intra (getf anchor :intra))
          (total (getf anchor :total)))
      (ensure (and (> wrvu 0) (> intra 0) (>= total intra))
              "Invalid raw task values for ~S" (getf anchor :id))
      (ensure (close-enough-p (getf anchor :wrvu-per-intra-service-hour)
                              (/ (* wrvu 60) intra))
              "Intra-service rate mismatch for ~S" (getf anchor :id))
      (ensure (close-enough-p (getf anchor :wrvu-per-total-physician-hour)
                              (/ (* wrvu 60) total))
              "Total-time rate mismatch for ~S" (getf anchor :id))))
  (format t "PASS: ~D points, ~D benchmarks, ~D CMS task anchors.~%"
          (length records) (length benchmarks) (length anchors)))
