(defparameter *here* (or *load-truename* *default-pathname-defaults*))
(defparameter *root* (merge-pathnames "../" *here*))
(defun one (p) (with-open-file (i p) (let ((x (read i nil :eof))) (assert (not (eq x :eof))) (assert (eq (read i nil :eof) :eof)) x)))
(let* ((training (one (merge-pathnames "data/specialty-training-paths.sexpr" *root*)))
       (data (one (merge-pathnames "data/specialty-nrmp-competitiveness.sexp" *root*)))
       (points (getf training :specialties)) (records (getf data :records)) (bench (getf data :benchmarks)))
  (assert (= 143 (length points) (length records)))
  (assert (= 94 (length bench)))
  (assert (equal (mapcar (lambda (x) (getf x :id)) points) (mapcar (lambda (x) (getf x :id)) records)))
  (assert (= (length records) (length (remove-duplicates (mapcar (lambda (x) (getf x :id)) records)))))
  (dolist (r records)
    (assert (plusp (getf r :candidates-per-position))) (assert (getf r :umap-use))
    (when (getf r :candidates)
      (assert (< (abs (- (getf r :candidates-per-position)
                         (/ (float (getf r :candidates) 1d0) (getf r :positions-offered)))) 1d-10))))
  (let ((derm (find :dermatology records :key (lambda (x) (getf x :id))))
        (card (find :interventional-cardiology records :key (lambda (x) (getf x :id)))))
    (assert (= 1099 (getf derm :candidates))) (assert (= 602 (getf derm :positions-offered)))
    (assert (= 247 (getf card :candidates))) (assert (= 307 (getf card :positions-offered))))
  (format t "PASS: 143 points; 94 direct NRMP benchmarks; arithmetic, IDs, order, and UMAP inclusion valid.~%"))
