(defparameter *here* (or *load-truename* *default-pathname-defaults*))
(defparameter *root* (merge-pathnames "../" *here*))
(defparameter *build-umap-run-main* nil)
(load (merge-pathnames "build-umap.lisp" *root*))
(let* ((report (read-form-file (merge-pathnames "output/specialty-umap-clusters.sexp" *root*)))
       (rows (read-csv-records (merge-pathnames "output/specialty-umap-embedding.csv" *root*)))
       (clusters (getf report :clusters))
       (members (mapcan (lambda (cluster) (copy-list (getf cluster :specialties))) clusters))
       (noise (getf report :noise-count)))
  (assert (eq (getf report :space) :two-dimensional-umap))
  (assert (eq (getf report :algorithm) :dbscan))
  (assert (= (length clusters) (getf report :cluster-count)))
  (assert (= 143 (+ (length members) noise)))
  (assert (= (length members) (length (remove-duplicates members :test #'string=))))
  (assert (= noise (count-if (lambda (row) (stringp (getf row :cluster-id))) rows)))
  (dolist (cluster clusters)
    (assert (plusp (getf cluster :size)))
    (assert (= (getf cluster :size) (length (getf cluster :specialties))))
    (assert (search (format nil "Cluster ~D:" (getf cluster :id)) (getf cluster :name))))
  (format t "PASS: ~D named DBSCAN clusters in 2D; ~D clustered and ~D unclustered specialties.~%"
          (length clusters) (length members) noise))
