#!/usr/bin/env sbcl --script

(defparameter *root* (make-pathname :name nil :type nil :defaults *load-truename*))
(defun read-one (relative)
  (with-open-file (stream (merge-pathnames relative *root*) :direction :input) (read stream)))
(defun ensure (condition control &rest arguments)
  (unless condition (apply #'error control arguments)))
(defun unique-p (items) (= (length items) (length (remove-duplicates items))))

(let* ((training (read-one "../data/specialty-training-paths.sexpr"))
       (data (read-one "../data/private-practice.sexp"))
       (point-ids (mapcar (lambda (x) (getf x :id)) (getf training :specialties)))
       (records (getf data :specialties))
       (record-ids (mapcar (lambda (x) (getf x :id)) records))
       (categories (getf data :source-categories))
       (category-ids (mapcar (lambda (x) (getf x :id)) categories)))
  (ensure (= 143 (length records)) "Expected 143 private-practice records")
  (ensure (equal point-ids record-ids) "Private-practice IDs/order differ from point universe")
  (ensure (unique-p record-ids) "Duplicate private-practice specialty ID")
  (ensure (unique-p category-ids) "Duplicate source category")
  (dolist (record records)
    (let ((value (getf record :private-practice-percent))
          (confidence (getf record :confidence)))
      (ensure (and (numberp value) (<= 0 value 100)) "Invalid percentage for ~S" (getf record :id))
      (ensure (member confidence '(:high :medium :low)) "Invalid confidence for ~S" (getf record :id))
      (ensure (member (getf record :source-category) category-ids) "Unknown category for ~S" (getf record :id))
      (ensure (eq t (getf record :umap-use)) "UMAP disabled for ~S" (getf record :id))))
  (format t "PASS: ~D points; high=~D medium=~D low=~D; all enabled for UMAP.~%"
          (length records)
          (count :high records :key (lambda (x) (getf x :confidence)))
          (count :medium records :key (lambda (x) (getf x :confidence)))
          (count :low records :key (lambda (x) (getf x :confidence)))))
