(defparameter *here* (or *load-truename* *default-pathname-defaults*))
(defparameter *root* (merge-pathnames "../" *here*))
(defun read-one (relative)
  (with-open-file (in (merge-pathnames relative *root*))
    (let ((value (read in nil :eof)))
      (assert (not (eq value :eof)))
      (assert (eq (read in nil :eof) :eof)) value)))
(let* ((training (read-one "data/specialty-training-paths.sexpr"))
       (data (read-one "data/specialty-sex-distribution.sexp"))
       (points (getf training :specialties))
       (records (getf data :records))
       (ids (mapcar (lambda (row) (getf row :id)) records)))
  (assert (= 143 (length records) (length (remove-duplicates ids))))
  (assert (equal ids (mapcar (lambda (row) (getf row :id)) points)))
  (dolist (row records)
    (let ((female (getf row :female-count)) (male (getf row :male-count))
          (unknown (getf row :sex-not-reported-count))
          (total (getf row :resident-count)) (percent (getf row :female-percent)))
      (assert (= total (+ female male unknown)))
      (assert (<= 0d0 percent 100d0))
      (assert (< (abs (- percent (* 100d0 (/ female (+ female male))))) 1d-5))
      (assert (member (getf row :confidence) '(:high :medium :low)))
      (assert (member (getf row :mapping) '(:direct :count-weighted-aggregate)))))
  (format t "PASS: 143 sex-distribution records; counts, order, percentages, and mappings valid.~%"))
