;;;; Nested grouped cross-validation and explicit missing-feature evaluation.
(defparameter *nine-rbf-main* nil)
(load (merge-pathnames "train-nine-rbf.lisp" (make-pathname :name nil :type nil :defaults *load-truename*)))
(defun nine-tune (train)
 (let* ((inner-train (remove-if (lambda (r) (zerop (mod (getf r :group) 4))) train))
        (inner-test (set-difference train inner-train)) (best nil) (score -1d10))
  (dolist (width '(0.3d0 0.5d0 0.8d0 1.2d0 2d0 3d0))
   (dolist (ridge '(0.001d0 0.01d0 0.1d0))
    (let* ((a (nine-fit inner-train width ridge)) (m (nine-measure a inner-train inner-test))
           (s (- (getf m :cluster-agreement) (* .01d0 (getf m :coordinate-rmse)))))
     (when (> s score) (setf score s best (list width ridge))))))
  best))
(defun nine-predict-partial (artifact input training)
 ;; Unknown dimensions are integrated over nearby observed contexts, never zero-filled.
 (let* ((stats (getf artifact :preprocessing))
        (nearest (subseq (sort (copy-list training) #'< :key
          (lambda (r) (loop for j below 5 sum (expt (/ (- (nth j input) (nth j (getf r :input))) (nth j (getf stats :scales))) 2)))) 0 5))
        (predictions (mapcar (lambda (r) (rbf-predict (getf artifact :model)
          (candidate-normalize (append (subseq input 0 5) (subseq (getf r :input) 5)) stats))) nearest))
        (means (apply #'mapcar (lambda (&rest vs) (/ (reduce #'+ vs) 5d0)) predictions))
        (scores (cddr means)))
  (nth (position (reduce #'max scores) scores) (getf artifact :classes))))
(defvar *nine-validation-main* t)
(when *nine-validation-main*
 (let ((rows (nine-observations)) folds (correct 0) (partial 0) (nearest 0) (position-correct 0))
  (dotimes (fold 5)
   (let* ((train (remove-if (lambda (r) (= (mod (getf r :group) 5) fold)) rows))
          (test (set-difference rows train)) (choice (nine-tune train))
          (model (nine-fit train (first choice) (second choice)))
          (metrics (nine-measure model train test))
          (baseline (nine-baseline (append (mapcar (lambda (r) (append (list :split :train) r)) train)
                                           (mapcar (lambda (r) (append (list :split :validation) r)) test))))
          (partial-correct (count-if (lambda (r) (equal (getf r :cluster) (nine-predict-partial model (getf r :input) train))) test)))
    (incf correct (getf metrics :correct)) (incf position-correct (getf metrics :coordinate-cluster-correct))
    (incf nearest (getf baseline :correct)) (incf partial partial-correct)
    (push (list :fold fold :selected choice :metrics metrics :nearest-neighbor baseline :five-known-correct partial-correct
                :training-ids (mapcar (lambda (r) (getf r :id)) train) :validation-ids (mapcar (lambda (r) (getf r :id)) test)) folds)
    (format t "Fold ~D: full ~D/~D; five known ~D; nearest ~D~%" fold (getf metrics :correct) (length test) partial-correct (getf baseline :correct))))
  (candidate-write (candidate-path "output/candidate-nine-cross-validation.sexp")
   (list :format :nested-grouped-validation :version 1 :total (length rows) :correct correct :coordinate-cluster-correct position-correct
         :five-known-correct partial :nearest-neighbor-correct nearest :folds (nreverse folds)
         :scope "Each specialty predicted once with its identical-five-input group excluded; hyperparameters selected on an inner split. Atlas and z features are fixed transductive references. Five-known uses exact atlas feature values, not validated questionnaire answers."))
  (format t "TOTAL full ~D/~D; five known ~D; nearest ~D; coordinate cluster ~D~%" correct (length rows) partial nearest position-correct)))
