#!/usr/bin/env sbcl --script

(defparameter *root* (make-pathname :name nil :type nil :defaults *load-truename*))
(defun read-one (relative)
  (with-open-file (stream (merge-pathnames relative *root*) :direction :input) (read stream)))
(defun ensure (condition control &rest arguments)
  (unless condition (apply #'error control arguments)))
(defun unique-p (items) (= (length items) (length (remove-duplicates items))))

(let* ((training (read-one "../data/specialty-training-paths.sexpr"))
       (data (read-one "../data/salaries.sexp"))
       (point-ids (mapcar (lambda (x) (getf x :id)) (getf training :specialties)))
       (records (getf data :specialties))
       (record-ids (mapcar (lambda (x) (getf x :id)) records))
       (sources (getf data :source-salaries))
       (source-ids (mapcar (lambda (x) (getf x :id)) sources)))
  (ensure (= 143 (length records)) "Expected 143 salary records")
  (ensure (equal point-ids record-ids) "Salary IDs/order differ from point universe")
  (ensure (unique-p record-ids) "Duplicate salary point")
  (ensure (= 41 (length sources)) "Expected 41 retained Marit categories")
  (ensure (unique-p source-ids) "Duplicate Marit salary category")
  (dolist (record records)
    (ensure (member (getf record :salary-donor-id) source-ids) "Unknown donor for ~S" (getf record :id))
    (ensure (> (getf record :average-total-compensation-usd) 0) "Invalid salary for ~S" (getf record :id))
    (ensure (member (getf record :confidence) '(:high :medium :low)) "Invalid confidence for ~S" (getf record :id))
    (ensure (eq t (getf record :umap-use)) "UMAP disabled for ~S" (getf record :id)))
  (let ((combined (find :hematology-and-medical-oncology records :key (lambda (x) (getf x :id))))
        (oncology (find :medical-oncology records :key (lambda (x) (getf x :id)))))
    (ensure (= 587000 (getf combined :average-total-compensation-usd)) "Wrong hematology/oncology salary")
    (ensure (= 638000 (getf oncology :average-total-compensation-usd)) "Wrong oncology-only salary")
    (ensure (not (eq (getf combined :salary-donor-id) (getf oncology :salary-donor-id)))
            "Oncology and hematology/oncology were collapsed"))
  (format t "PASS: ~D points; high=~D medium=~D low=~D; oncology categories distinct.~%"
          (length records)
          (count :high records :key (lambda (x) (getf x :confidence)))
          (count :medium records :key (lambda (x) (getf x :confidence)))
          (count :low records :key (lambda (x) (getf x :confidence)))))
